Repository Alcancia-io/Alcancia-FrontEnd, pull requests merged in 2024-02, with the labels that each got.

#266 Feat/OINK-1367 | Implement Firebase Remote Configs
  lib/firebase_remote_config.dart
  lib/main.dart
  lib/src/resources/images/icon_us_flag.png
  lib/src/screens/checkout/checkout.dart
  lib/src/screens/dashboard/dashboard_screen.dart
  lib/src/screens/login/login_screen.dart
  lib/src/screens/swap/swap_screen.dart
  lib/src/screens/transaction_detail/transaction_detail.dart
  lib/src/screens/withdraw/withdraw_screen.dart
  lib/src/shared/models/bank_info_item.dart
  lib/src/shared/models/checkout_model.dart
  lib/src/shared/models/remote_config_data.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, fix

#270 Fixes iOS Deployment issues with CocoaPods Version mismatches
  lib/src/shared/services/metamap_service.dart
  pubspec.lock
  pubspec.yaml
Labels: fix, deployment

#284 feat/OINK-1413 | USD Withdrawal/Deposit Spreads from Remote Configs
  lib/src/resources/l10n/app_en.arb
  lib/src/resources/l10n/app_es.arb
  lib/src/screens/forgot_password/forgot_password.dart
  lib/src/screens/swap/swap_screen.dart
  lib/src/screens/withdraw/withdraw_screen.dart
  lib/src/shared/models/remote_config_data.dart
Labels: enhancement, Transaction

#286 v1.5.6 Release
  ios/Podfile.lock
  lib/firebase_remote_config.dart
  lib/main.dart
  lib/src/resources/images/arrow_down_purple.svg
  lib/src/resources/images/icon_us_flag.png
  lib/src/resources/l10n/app_en.arb
  lib/src/resources/l10n/app_es.arb
  lib/src/screens/checkout/checkout.dart
  lib/src/screens/dashboard/dashboard_screen.dart
  lib/src/screens/swap/swap_screen.dart
  lib/src/screens/transaction_detail/transaction_detail.dart
  lib/src/screens/withdraw/crypto_withdraw_screen.dart
  lib/src/screens/withdraw/withdraw_controller.dart
  lib/src/screens/withdraw/withdraw_screen.dart
  lib/src/shared/extensions/type_extensions.dart
  lib/src/shared/graphql/queries/get_crypto_withdrawal_fee_query.dart
  lib/src/shared/models/bank_info_item.dart
  lib/src/shared/models/checkout_model.dart
  lib/src/shared/models/remote_config_data.dart
  lib/src/shared/services/crypto_wallet_service.dart
  lib/src/shared/services/metamap_service.dart
  pubspec.lock
  pubspec.yaml
Labels: Release

#287 Hotfix: MXN Users Unable to WIthdraw and Showing incorrect Exchange in Deposit
  lib/src/screens/swap/swap_screen.dart
  lib/src/screens/withdraw/withdraw_screen.dart
Labels: hotfix, Transaction

#289 Hotfix v1.5.7 Release
  lib/src/screens/swap/swap_screen.dart
  lib/src/screens/withdraw/withdraw_screen.dart
Labels: hotfix, Release

#294 Hotfix Release v1.5.8
  lib/src/screens/swap/swap_screen.dart
Labels: hotfix, Release

#295 Fix: Incorrect Default Currency getting set
  lib/src/screens/swap/swap_screen.dart
Labels: fix, Transaction

#296 Fixes issues caused by disabling MX in remote config
  lib/src/screens/swap/swap_screen.dart
  lib/src/screens/withdraw/withdraw_screen.dart
Labels: fix, Transaction

#299 Fixes: Empty Defaults and bad UI for Country Selector
  lib/src/screens/swap/swap_screen.dart
  lib/src/screens/withdraw/withdraw_screen.dart
Labels: fix, Transaction, UI/UX

#303 Release v1.5.8
  lib/src/screens/swap/swap_screen.dart
  lib/src/screens/withdraw/withdraw_screen.dart
Labels: Release

#285 OINK-1394 | Update Forgot Password Messaging
  lib/src/screens/forgot_password/forgot_password.dart
  lib/src/shared/graphql/queries/forgot_password_query.dart
Labels: enhancement, Auth

#290 OINK-1414 & OINK-1395 | Tranfer Funds error messages
  lib/src/resources/l10n/app_en.arb
  lib/src/resources/l10n/app_es.arb
  lib/src/screens/transfer/transfer_screen.dart
Labels: enhancement, UI/UX

#291 Change Label on Withdraw amount
  lib/src/screens/withdraw/withdraw_screen.dart
Labels: enhancement, UI/UX

#301 OINK-1412 | Implement Refresh Token
  lib/src/shared/graphql/mutations/refresh_token_mutation.dart
  lib/src/shared/provider/router_provider.dart
  lib/src/shared/services/auth_service.dart
  lib/src/shared/services/biometric_service.dart
Labels: enhancement, Auth, UI/UX
