Repository Alcancia-io/Alcancia-FrontEnd, pull requests merged in 2024-01, with the labels that each got.

#221 OINK-1347 - migrate me query
  lib/src/features/registration/model/registration_controller.dart
  lib/src/features/registration/presentation/otp_screen.dart
  lib/src/features/registration/presentation/phone_registration_screen.dart
  lib/src/features/user-profile/presentation/user_profile_screen.dart
  lib/src/screens/dashboard/dashboard_controller.dart
  lib/src/screens/login/login_screen.dart
  lib/src/shared/graphql/mutations/delete_account_mutation.dart
  lib/src/shared/graphql/queries/get_authenticated_user_query.dart
  lib/src/shared/graphql/queries/index.dart
  lib/src/shared/graphql/queries/is_authenticated_query.dart
  lib/src/shared/graphql/queries/logout_query.dart
  lib/src/shared/provider/router_provider.dart
  lib/src/shared/services/auth_service.dart
  lib/src/shared/services/user_service.dart
Labels: Migration, Auth

#229 #228 Update Staging Branch
  .gitignore
  amplify/hooks/post-push.sh.sample
  amplify/hooks/pre-push.js.sample
  lib/src/features/registration/model/registration_controller.dart
  lib/src/features/registration/presentation/otp_screen.dart
  lib/src/screens/account_verification.dart
  lib/src/screens/biometric/biometric_authentication_screen.dart
  lib/src/screens/login/login_controller.dart
  lib/src/screens/login/login_screen.dart
  lib/src/screens/login/mfa_screen.dart
  lib/src/shared/provider/router_provider.dart
  lib/src/shared/services/auth_service.dart
Labels: Tech Debt

#223 OINK-1350 | Migrate "generateUserToken" Query
  lib/src/features/registration/presentation/otp_screen.dart
  lib/src/features/user-profile/presentation/user_profile_screen.dart
  lib/src/screens/dashboard/dashboard_controller.dart
  lib/src/shared/graphql/queries/jwt_zendesk_query.dart
  lib/src/shared/models/jwt_zendesk.dart
  lib/src/shared/provider/router_provider.dart
  lib/src/shared/services/auth_service.dart
Labels: Zendesk, Migration, Customer Support

#224 OINK-1349 | Migrate "userPhoneNumberSearch" Query
  lib/src/screens/login/login_screen.dart
  lib/src/screens/transfer/transfer_controller.dart
  lib/src/shared/graphql/queries/user_phone_number_search_query.dart
  lib/src/shared/services/auth_service.dart
  lib/src/shared/services/user_service.dart
Labels: Migration, Transaction

#231 Fix/stage sign in
  lib/src/shared/services/auth_service.dart
Labels: fix, Auth

#241 fix/OINK-1368 | Biometrics Verification not Working in Staging
  lib/src/screens/login/login_screen.dart
  lib/src/screens/login/mfa_screen.dart
Labels: fix, Auth, Stage

#242 hotfix/OINK-1371 | Transfer Screen Throwing Error
  lib/src/shared/graphql/queries/user_phone_number_search_query.dart
  lib/src/shared/services/user_service.dart
Labels: fix, Transaction, Stage

#245 feat/OINK-1375 | Migrate alcanciaExternalWithdraw to executeCryptoWithdrawal
  lib/src/screens/withdraw/withdraw_controller.dart
  lib/src/shared/graphql/mutations/external_withdraw_query.dart
  lib/src/shared/graphql/queries/external_withdraw_query.dart
  lib/src/shared/models/external_withdrawal.dart
  lib/src/shared/services/crypto_wallet_service.dart
Labels: Migration, Transaction

#249 hotfix/OINK-1378 | Hotfix Forgot Password Messaging Error from Develop
  lib/src/screens/forgot_password/forgot_password.dart
Labels: fix, Auth

#251 Chore/update stage
  ios/Runner/Info.plist
  lib/src/screens/biometric/biometric_authentication_screen.dart
  lib/src/screens/login/login_screen.dart
  lib/src/screens/swap/swap_screen.dart
  lib/src/screens/withdraw/withdraw_screen.dart
Labels: Stage, chore

#252 OINK-1382 | Fix UpdateAuthUser Mutation
  lib/src/shared/graphql/mutations/update_authenticated_user_mutation.dart
  lib/src/shared/services/user_service.dart
Labels: fix, Stage, KYC

#253 Chore/migrate transfer query
  lib/src/resources/l10n/app_en.arb
  lib/src/resources/l10n/app_es.arb
  lib/src/screens/successful_transaction/successful_transaction.dart
  lib/src/screens/transfer/transfer_controller.dart
  lib/src/screens/transfer/transfer_screen.dart
  lib/src/shared/components/alcancia_confirmation_dialog.dart
  lib/src/shared/graphql/queries/execute_p2p_tranfer_mutation.dart
  lib/src/shared/graphql/queries/transfer_funds_query.dart
  lib/src/shared/models/transfer_response_model.dart
  lib/src/shared/services/transactions_service.dart
Labels: Migration, Transaction

#257 OINK-1385 | Fix Crypto Withdrawal Error
  lib/src/shared/models/external_withdrawal.dart
Labels: fix, Transaction, Stage

#259 Fix Stage Merge Conflicts
  lib/src/screens/forgot_password/forgot_password.dart
Labels: fix

#260 Fix/stage conflicts
  lib/src/resources/l10n/app_en.arb
  lib/src/screens/login/login_screen.dart
  lib/src/shared/provider/router_provider.dart
Labels: fix

#258 Release v1.5.5
  .gitignore
  amplify/hooks/post-push.sh.sample
  amplify/hooks/pre-push.js.sample
  lib/main.dart
  lib/src/features/registration/data/signup_mutation.dart
  lib/src/features/registration/model/registration_controller.dart
  lib/src/features/registration/presentation/otp_screen.dart
  lib/src/features/registration/presentation/phone_registration_screen.dart
  lib/src/features/user-profile/presentation/user_profile_screen.dart
  lib/src/resources/l10n/app_en.arb
  lib/src/resources/l10n/app_es.arb
  lib/src/screens/account_verification.dart
  lib/src/screens/biometric/biometric_authentication_screen.dart
  lib/src/screens/dashboard/dashboard_controller.dart
  lib/src/screens/dashboard/dashboard_screen.dart
  lib/src/screens/forgot_password/forgot_password.dart
  lib/src/screens/login/login_controller.dart
  lib/src/screens/login/login_screen.dart
  lib/src/screens/login/mfa_screen.dart
  lib/src/screens/successful_transaction/successful_transaction.dart
  lib/src/screens/transfer/transfer_controller.dart
  lib/src/screens/transfer/transfer_screen.dart
  lib/src/screens/withdraw/withdraw_controller.dart
  lib/src/shared/components/alcancia_confirmation_dialog.dart
  lib/src/shared/components/alcancia_transaction_item.dart
  lib/src/shared/extensions/type_extensions.dart
  lib/src/shared/graphql/mutations/complete_forgot_password_mutation.dart
  lib/src/shared/graphql/mutations/complete_mfa_sign_in_mutation.dart
  lib/src/shared/graphql/mutations/delete_account_mutation.dart
  lib/src/shared/graphql/mutations/external_withdraw_query.dart
  lib/src/shared/graphql/mutations/login_mutation.dart
  lib/src/shared/graphql/mutations/signin_mutation.dart
  lib/src/shared/graphql/mutations/signup_mutation.dart
  lib/src/shared/graphql/mutations/update_authenticated_user_mutation.dart
  lib/src/shared/graphql/mutations/update_user_mutation.dart
  lib/src/shared/graphql/queries/execute_p2p_tranfer_mutation.dart
  lib/src/shared/graphql/queries/external_withdraw_query.dart
  lib/src/shared/graphql/queries/forgot_password_query.dart
  lib/src/shared/graphql/queries/get_authenticated_user_query.dart
  lib/src/shared/graphql/queries/index.dart
  lib/src/shared/graphql/queries/is_authenticated_query.dart
  lib/src/shared/graphql/queries/jwt_zendesk_query.dart
  lib/src/shared/graphql/queries/logout_query.dart
  lib/src/shared/graphql/queries/transfer_funds_query.dart
  lib/src/shared/graphql/queries/user_phone_number_search_query.dart
  lib/src/shared/models/MFAModel.dart
  lib/src/shared/models/external_withdrawal.dart
  lib/src/shared/models/jwt_zendesk.dart
  lib/src/shared/models/login_data_model.dart
  lib/src/shared/models/transaction_input_model.dart
  lib/src/shared/models/transaction_model.dart
  lib/src/shared/models/transfer_response_model.dart
  lib/src/shared/provider/router_provider.dart
  lib/src/shared/services/auth_service.dart
  lib/src/shared/services/crypto_wallet_service.dart
  lib/src/shared/services/transactions_service.dart
  lib/src/shared/services/user_service.dart
Labels: Release

#261 Fix/formatting issue
  lib/src/screens/login/login_screen.dart
Labels: fix

#262 OINK-1377 | Implement getCryptoWithdrawalFee
  lib/src/screens/withdraw/crypto_withdraw_screen.dart
  lib/src/screens/withdraw/withdraw_controller.dart
  lib/src/shared/graphql/queries/get_crypto_withdrawal_fee_query.dart
  lib/src/shared/services/crypto_wallet_service.dart
Labels: refactor, Transaction

#263 OINK-1387 | Forgot Password Error
  lib/src/screens/forgot_password/forgot_password.dart
Labels: hotfix, Auth
